### PR TITLE
New component added

### PR DESCRIPTION
**Pull request by Himanxu1**
Added A seek slider and change some CSS .

### CODE REVIEW

**Comment by arpanaditya** [comment]
Thank you for your contribution. WIll review it soon :)

**Review by arpanaditya — CHANGES_REQUESTED** [review]
Hey, I have viewed your code and have checked them, but the seek slider is not working. Please check the code again. may be add some screenshot or video for reference. If you want we can block a time in our calendar and also have a meet and discuss this feature together and troubleshoot what's the project. 
Please check the codes and confirm.

**Comment by arpanaditya** [comment]
You can book a slot here: https://calendly.com/arpanaditya
Looking forward to it @Himanxu1

**Comment by Himanxu1** [comment]
Ya, that slider is not working due to some issuw which i can't get .
I have scheduled a 15 min meeting with you on 3 march . we can discuss some other features as well.

**Pull request closed without merging**
